apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              {{- if .Values.secrets.useKubernetesSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: OPENAI_API_KEY
              {{- else }}
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
              {{- end }}
            - name: QDRANT_URL
              value: {{ .Values.env.QDRANT_URL | quote }}
            - name: RUST_SERVICE_URL
              value: {{ .Values.env.RUST_SERVICE_URL | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}