apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
  type: {{ .Values.service.type }}
