apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.global.scrape_interval }}
      evaluation_interval: {{ .Values.config.global.evaluation_interval }}

    scrape_configs:
      {{- range .Values.config.scrape_configs }}
      - job_name: {{ .job_name | quote }}
        static_configs:
          - targets: 
            {{- range .static_configs }}
            {{- range .targets }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}
        metrics_path: {{ .metrics_path | quote }}
        scrape_interval: {{ .scrape_interval }}
        {{- if .scrape_timeout }}
        scrape_timeout: {{ .scrape_timeout }}
        {{- end }}
      {{- end }}
