replicaCount: 1

image:
  repository: backend
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  OPENAI_API_KEY: "dummy-key" # Replace in real secrets
  QDRANT_URL: "http://qdrant:6333"
  RUST_SERVICE_URL: "http://rust_accelerator:5000"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
