name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push images
        run: |
          # Build backend
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} ./backend
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          
          # Build rust
          docker build -t ghcr.io/${{ github.repository }}/rust-accelerator:${{ github.sha }} ./rust_accelerator  
          docker push ghcr.io/${{ github.repository }}/rust-accelerator:${{ github.sha }}
      
      - name: Deploy to Kubernetes
        if: ${{ secrets.KUBE_CONFIG != '' }}
        run: |
          # Setup kubectl
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          
          # Update image tags in Helm values
          helm upgrade --install qdrant-backend ./helm/backend \
            --set image.tag=${{ github.sha }} \
            --set image.repository=ghcr.io/${{ github.repository }}/backend \
            --namespace qdrant-ai --create-namespace
            
          helm upgrade --install qdrant-rust ./helm/rust-accelerator \
            --set image.tag=${{ github.sha }} \
            --set image.repository=ghcr.io/${{ github.repository }}/rust-accelerator \
            --namespace qdrant-ai --create-namespace
