name: Test & Lint
on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: cd backend && poetry install --no-root
      - name: Run tests
        run: cd backend && poetry run pytest
      - name: Lint
        run: cd backend && poetry run ruff check .

  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        run: cd rust_accelerator && cargo test
      - name: Lint
        run: cd rust_accelerator && cargo clippy -- -D warnings
